volumes:
  kc_data:
    name: keycloak-extensions-demo-data
services:
  keycloak:
    container_name: keycloak-extensions-playground
    image: quay.io/keycloak/keycloak:26.0.0
    command: start-dev
    environment:
      DEBUG: "true"
      DEBUG_PORT: "*:8787"
      KC_FEATURES: preview
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8090:8080"
      - "8787:8787"
    volumes:
      - kc_data:/opt/keycloak/data
      - ./keycloak-demo/target/keycloak-demo-1.0-SNAPSHOT.jar:/opt/keycloak/providers/keycloak-demo-1.0-SNAPSHOT.jar
    extra_hosts:
      - "host.docker.internal:host-gateway"
